name: CI Trivy Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  trivy:
    name: Trivy Scan
    uses: CodeForgeGuild/ci-actions/.github/workflows/trivy-scan.yml@v0
